name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Docker Container on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          debug: true
          script: |
            cd terraform-aws-devops-project
            git pull

            docker build -t devops-web:latest ./docker

            docker save devops-web:latest -o devops-web.tar

            sudo k3s ctr images import devops-web.tar

            kubectl apply -f kubernetes/

            kubectl rollout restart deployment devops-web

            kubectl get pods
